#!/bin/bash

VIM_HOME=~/.vim

if [ ! -d "$VIM_HOME" ]; then
  mkdir $VIM_HOME
fi

if [ ! -d "$VIM_HOME/autoload" ]; then
  mkdir "$VIM_HOME/autoload"
fi

if [ ! -d "$VIM_HOME/bundle" ]; then
  mkdir "$VIM_HOME/bundle"
fi

curl -Sso "$VIM_HOME/autoload/pathogen.vim" \
  https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

cd "$VIM_HOME/bundle"

git clone https://github.com/$1
