#!/bin/bash

VIM_HOME=~/.vim

if [ ! -e "$VIM_HOME/autoload/pathogen.vim" ]; then
  mkdir -p "$VIM_HOME/autoload"
  curl -Sso "$VIM_HOME/autoload/pathogen.vim" \
    https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
fi

mkdir -p "$VIM_HOME/bundle"

cd "$VIM_HOME/bundle"

git clone https://github.com/$1
